server:
  port: 8080
  error:
    include-exception: false
    include-message: always
    include-stacktrace: ON_PARAM
    whitelabel:
      enabled: true

spring:
  application:
    name: backend

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  messages:
    encoding: UTF-8

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

auth:
  secretKey: 'uNlQ1xD8WRKNhG7P0Kns2+wUw1oYImUgUOcMmLyW7R0='
  tokenExpiry: 18000000